ALTER TABLE `mindliner5`.`objects_containermap_links` ADD COLUMN `CENTER` DOUBLE UNSIGNED NULL  AFTER `CONTAINER_MAP_ID` , ADD COLUMN `SOURCE_OFFSET` DOUBLE UNSIGNED NULL  AFTER `CENTER` , ADD COLUMN `TARGET_OFFSET` DOUBLE UNSIGNED NULL  AFTER `SOURCE_OFFSET` ;

ALTER TABLE `mindliner5`.`objects_containermap_links` ADD COLUMN `SOURCE_POSITION` VARCHAR(16) NULL  AFTER `TARGET_OFFSET` , ADD COLUMN `TARGET_POSITION` VARCHAR(16) NULL  AFTER `SOURCE_POSITION` ;

ALTER TABLE `mindliner5`.`objects_containermap_links` CHANGE COLUMN `SOURCE_POSITION` `SOURCE_POSITION` VARCHAR(16) NULL DEFAULT 'RIGHT'  , CHANGE COLUMN `TARGET_POSITION` `TARGET_POSITION` VARCHAR(16) NULL DEFAULT 'RIGHT'  ;