/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mindliner.categories;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * This class describes the type of a news record
 *
 * @author Marius Messerli
 */
@Entity
@Table(name = "newstypes")
@NamedQueries({
    @NamedQuery(name = "MlsNewsType.findByTag", query = "SELECT n FROM MlsNewsType n WHERE n.tag = :tag"),
    @NamedQuery(name = "MlsNewsType.findAll", query = "SELECT n FROM MlsNewsType n")
})

public class MlsNewsType extends mlsMindlinerCategory implements Serializable {

    private boolean persistent = false;
    private String tag = "";
    private static final long serialVersionUID = 19640205L;

    public void setPersistent(boolean p) {
        persistent = p;
    }

    /**
     * Evaluates whether this action item is persitent or not. This is a strange
     * field for an entity bean, I know. However, the class is also used for
     * action items that are generated by the server on the fly and are never
     * persisted. Example: "Upcoming tasks" are generated by the session bean
     * that is crawling the tasks and there is no use in persisting this.
     *
     * @return True if this type is persistent in the DB, false if it is
     * transient.
     */
    @Column(name = "PERSISTENT")
    public boolean isPersistent() {
        return persistent;
    }

    public void setTag(String t) {
        tag = t;
    }

    @Column(name = "TAG")
    public String getTag() {
        return tag;
    }

}
