INSERT INTO links (HOLDER_ID,RELATIVE_ID,LABEL,OWNER_ID,MODIFICATION_TS,CREATION_TS,CLIENT_ID,RELATIVE_TYPE)
SELECT oo.HOLDER_ID,oo.RELATIVE_ID, null, o.OWNER_ID, o.MODIFICATION, o.CREATION_DATE, o.CLIENT_ID,0
FROM objects_objects oo, objects o WHERE o.ID = oo.HOLDER_ID;