/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mindliner.connector;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Dominic Plangger
 */
public class GoogleDriveAuthenticationPanel extends javax.swing.JPanel {
    
    
    private GoogleDriveAuthenticationDialog dialog = null;
    private String url = null;

    /**
     * Creates new form CloudAuthenticationPanel
     */
    public GoogleDriveAuthenticationPanel() {
        initComponents();
    }

    public void setDialog(GoogleDriveAuthenticationDialog dialog) {
        this.dialog = dialog;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    
    public String getCode() {
        return CodeInput.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        CodeInput = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        FinishButton = new javax.swing.JButton();
        TextPane = new javax.swing.JTextPane();
        AuthenticationLink = new org.jdesktop.swingx.JXHyperlink();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+6));
        jLabel1.setText("Google Drive Authentication");

        jLabel2.setText("Paste code from Google here");

        FinishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/2424/floppy_disk_blue.png"))); // NOI18N
        FinishButton.setText("OK");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        TextPane.setBackground(new java.awt.Color(240, 240, 240));
        TextPane.setBorder(null);
        TextPane.setText("Before Mindliner can upload files to your Google Drive account you need to authorise Mindliner once. Please follow this link and copy back the code after you granted Mindliner access.");
        TextPane.setAutoscrolls(false);

        AuthenticationLink.setText("Link");
        AuthenticationLink.setFont(AuthenticationLink.getFont().deriveFont(AuthenticationLink.getFont().getSize()+3f));
        AuthenticationLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthenticationLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FinishButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(AuthenticationLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AuthenticationLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FinishButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        String code = CodeInput.getText();
        if (code == null || code.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid Code. Please copy paste the code from the Google page into the input field.", "Invalid Code", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dialog.setVisible(false);
    }//GEN-LAST:event_FinishButtonActionPerformed

    private void AuthenticationLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthenticationLinkActionPerformed
        boolean success = false;
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI(url));
                success = true;
            } catch (IOException ex) {
                Logger.getLogger(GoogleDriveAuthenticationPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(GoogleDriveAuthenticationPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (!success) {
            JTextArea textarea = new JTextArea("Cannot open browser. Please open the following URL manually in your browser. \n\n" + url);
            textarea.setEditable(true);
            JOptionPane.showMessageDialog(null, textarea, "Cannot open browser", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AuthenticationLinkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink AuthenticationLink;
    private javax.swing.JFormattedTextField CodeInput;
    private javax.swing.JButton FinishButton;
    private javax.swing.JTextPane TextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
