ALTER TABLE `mindliner5`.`users` 
ADD COLUMN `FIRST_NAME` VARCHAR(128) NULL , 
ADD COLUMN `LAST_NAME` VARCHAR(128) NULL ,
ADD COLUMN `EMAIL` VARCHAR(128) NULL ;

UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Marius', `LAST_NAME`='Messerli', `EMAIL`='marius.messerli@mindliner.com' WHERE `ID`='1';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Peter', `LAST_NAME`='Majer' WHERE `ID`='2';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Mike', `LAST_NAME`='Wussow' WHERE `ID`='3';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Christoph', `LAST_NAME`='Laimer', `EMAIL`='christoph@bitplane.com' WHERE `ID`='4';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Michael', `LAST_NAME`='Gähwiler', `EMAIL`='michael@bitplane.com' WHERE `ID`='5';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Luciano', `LAST_NAME`='Lucas', `EMAIL`='luciano@bitplane.com' WHERE `ID`='7';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Roswitha', `LAST_NAME`='Hoffelner' WHERE `ID`='9';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Kerstin', `LAST_NAME`='Fink' WHERE `ID`='10';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Sylvain', `LAST_NAME`='Anderegg' WHERE `ID`='11';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Igor', `LAST_NAME`='Beati', `EMAIL`='igor@bitplane.com' WHERE `ID`='12';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Dieter', `LAST_NAME`='Göhlmann' WHERE `ID`='13';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Kevin', `LAST_NAME`='Frischmann', `EMAIL`='kevin@bitplane.com' WHERE `ID`='14';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Arvonn', `LAST_NAME`='Tully', `EMAIL`='arvonn@bitplane.com' WHERE `ID`='15';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Matt', `LAST_NAME`='Holecko' WHERE `ID`='16';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Kaethe', `LAST_NAME`='Beck' WHERE `ID`='17';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Patrick', `LAST_NAME`='Moser' WHERE `ID`='18';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Daniel', `LAST_NAME`='Reisen' WHERE `ID`='19';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Marius', `LAST_NAME`='Messerli', `EMAIL`='marius.messerli@mindliner.com' WHERE `ID`='21';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Niklaus', `LAST_NAME`='Messerli', `EMAIL`='niklaus@mess.ch' WHERE `ID`='22';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Michael', `LAST_NAME`='Wirth' WHERE `ID`='24';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Christine', `LAST_NAME`='Brink' WHERE `ID`='25';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Cory', `LAST_NAME`='Glowinsky' WHERE `ID`='26';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Yier', `LAST_NAME`='Toh' WHERE `ID`='27';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Michael', `LAST_NAME`='Mahlert' WHERE `ID`='28';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Mario', `LAST_NAME`='Emmenlauer' WHERE `ID`='29';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Sacha', `LAST_NAME`='Bäbler' WHERE `ID`='30';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Irena', `LAST_NAME`='Paunovic' WHERE `ID`='31';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Lijun', `LAST_NAME`='Wu' WHERE `ID`='32';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Marius', `LAST_NAME`='Messerli', `EMAIL`='marius@mess.ch' WHERE `ID`='33';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Jochen', `LAST_NAME`='Scheld' WHERE `ID`='36';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Felix', `LAST_NAME`='Gorny', `EMAIL`='felix@bitplane.com' WHERE `ID`='39';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Xuan', `LAST_NAME`='Zhang', `EMAIL`='xuan@bitplane.com' WHERE `ID`='40';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Marcin' WHERE `ID`='41';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Niklaus', `LAST_NAME`='Messerli', `EMAIL`='niklaus@mess.ch' WHERE `ID`='43';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Bernard', `LAST_NAME`='Quinn' WHERE `ID`='48';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Yier', `LAST_NAME`='Toh' WHERE `ID`='49';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='One', `LAST_NAME`='Guest' WHERE `ID`='50';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Two', `LAST_NAME`='Guest' WHERE `ID`='51';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Three', `LAST_NAME`='Guest' WHERE `ID`='52';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Four', `LAST_NAME`='Guest' WHERE `ID`='53';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Five', `LAST_NAME`='Guest' WHERE `ID`='54';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Six', `LAST_NAME`='Guest' WHERE `ID`='55';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Seven', `LAST_NAME`='Guest' WHERE `ID`='56';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Eight', `LAST_NAME`='Guest' WHERE `ID`='57';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Nine', `LAST_NAME`='Guest' WHERE `ID`='58';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Niklaus', `LAST_NAME`='Messerli', `EMAIL`='niklaus@mess.ch' WHERE `ID`='59';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Benjamin', `LAST_NAME`='Ching', `EMAIL`='ben@metasystems-asia.com' WHERE `ID`='60';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Erik' WHERE `ID`='61';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Kevin', `LAST_NAME`='Neoh' WHERE `ID`='62';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Bryan Yuen', `LAST_NAME`='Yi Kong' WHERE `ID`='63';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Queenie', `LAST_NAME`='So' WHERE `ID`='64';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Ada', `LAST_NAME`='Wong' WHERE `ID`='65';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Danny', `LAST_NAME`='Poon' WHERE `ID`='66';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='René', `LAST_NAME`='Lenoir' WHERE `ID`='67';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Won Yung', `LAST_NAME`='Choi' WHERE `ID`='68';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Meta', `LAST_NAME`='Guest' WHERE `ID`='69';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Christian', `LAST_NAME`='Plattner' WHERE `ID`='70';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Lea', `LAST_NAME`='Plattner' WHERE `ID`='71';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Niklaus', `LAST_NAME`='Messerli', `EMAIL`='niklaus@mess.ch' WHERE `ID`='72';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Luciano', `LAST_NAME`='Lucas', `EMAIL`='luciano@bitplane.com' WHERE `ID`='73';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Daniel', `LAST_NAME`='Reisen', `EMAIL`='daniel@bitplane.com' WHERE `ID`='74';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Won Yung', `LAST_NAME`='Choi' WHERE `ID`='75';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Anna' WHERE `ID`='76';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Min', `LAST_NAME`='Zhou' WHERE `ID`='77';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Vinay' WHERE `ID`='78';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Trainer' WHERE `ID`='79';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Stefan', `LAST_NAME`='Baur', `EMAIL`='sb@katta.ch' WHERE `ID`='80';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Edi', `LAST_NAME`='Füllemann', `EMAIL`='ef@katta.ch' WHERE `ID`='81';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Bernad', `LAST_NAME`='Quinn' WHERE `ID`='82';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Michael', `LAST_NAME`='Wussow' WHERE `ID`='83';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Niklaus', `LAST_NAME`='Messerli', `EMAIL`='niklaus@mess.ch' WHERE `ID`='84';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Adrian', `LAST_NAME`='Wahl' WHERE `ID`='85';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Dominic', `LAST_NAME`='Plangger', `EMAIL`='dominic.plangger@mindliner.com' WHERE `ID`='86';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Kevin', `LAST_NAME`='Cowan' WHERE `ID`='87';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Eamonn', `LAST_NAME`='Boyle' WHERE `ID`='88';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Gary', `LAST_NAME`='Wilmot' WHERE `ID`='89';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Gerraint', `LAST_NAME`='Wilde' WHERE `ID`='90';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Mark', `LAST_NAME`='Browne' WHERE `ID`='91';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Donal', `LAST_NAME`='Denvir' WHERE `ID`='92';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='Marius', `LAST_NAME`='Messerli', `EMAIL`='marius.messerli@mindliner.com' WHERE `ID`='93';
UPDATE `mindliner5`.`users` SET `FIRST_NAME`='James', `LAST_NAME`='Ewans' WHERE `ID`='94';
