/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mindliner.main;

import com.mindliner.cache.CacheEngineStatic;
import com.mindliner.cache.DefaultObjectAttributes;
import com.mindliner.categories.mlsPriority;
import com.mindliner.gui.MlDialogUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 * This dialog lets the user manage his/her object default attributes.
 * 
 * @author Marius Messerli
 */
public class ObjectDefaultsDialog extends javax.swing.JDialog {

    /**
     * Creates new form ObjectDefaultsDialog
     *
     * @param parent The parent frame
     * @param modal Whether or not the dialog is to be modal
     */
    public ObjectDefaultsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configureComponents();
    }

    private void configureComponents() {

        // Priority
        DefaultComboBoxModel dbm = new DefaultComboBoxModel();
        List<mlsPriority> plist = CacheEngineStatic.getPriorities();
        plist.stream().forEach((p) -> {
            dbm.addElement(p);
        });
        PriorityCombo.setModel(dbm);
        ObjectAccess.setShowAlways(true);
        ObjectAccess.configureComponents();
        ObjectAccess.addDataPoolActionListener((ActionEvent e) -> {
            DefaultObjectAttributes.setDataPoolId(ObjectAccess.getDataPool().getId());
        });
        ObjectAccess.addConfidentialityActionListener((ActionEvent e) -> {
            DefaultObjectAttributes.setConfidentiality(ObjectAccess.getConfidentiality());
        });
        MlDialogUtils.addEscapeListener(this);
        updateDefaultsDialog();
    }

    /**
     * reads the values from the DefaultObjectAttributes class and updates the
     * corresponding controls before showing the dialog
     */
    private void updateDefaultsDialog() {
        PriorityCombo.setSelectedItem(DefaultObjectAttributes.getPriority());
        UpdateDefaults.setSelected(DefaultObjectAttributes.isAdoptLastEdit());
        ObjectAccess.configureComponents();
        AEDPrivacyCheckbox.setSelected(DefaultObjectAttributes.getPrivateAccess());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObjectAccess = new com.mindliner.gui.ObjectAccessControls();
        PriorityCombo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        AEDPrivacyCheckbox = new javax.swing.JCheckBox();
        UpdateDefaults = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/resources/GeneralEditor"); // NOI18N
        setTitle(bundle.getString("ObjectDefaultsDialogTitle")); // NOI18N

        PriorityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PriorityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityComboActionPerformed(evt);
            }
        });

        jLabel19.setText(bundle.getString("AEDPriority")); // NOI18N

        AEDPrivacyCheckbox.setText(bundle.getString("DefaultsPrivateChexbox")); // NOI18N
        AEDPrivacyCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEDPrivacyCheckboxActionPerformed(evt);
            }
        });

        UpdateDefaults.setSelected(true);
        UpdateDefaults.setText(bundle.getString("AEDUpdateOnEdits")); // NOI18N
        UpdateDefaults.setToolTipText(bundle.getString("AEDUpdateWithLastTT")); // NOI18N
        UpdateDefaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDefaultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ObjectAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PriorityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AEDPrivacyCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125))
                    .addComponent(UpdateDefaults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ObjectAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PriorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AEDPrivacyCheckbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateDefaults)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateDefaultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDefaultsActionPerformed
        DefaultObjectAttributes.setAdoptLastEdit(UpdateDefaults.isSelected());
    }//GEN-LAST:event_UpdateDefaultsActionPerformed

    private void AEDPrivacyCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEDPrivacyCheckboxActionPerformed
        DefaultObjectAttributes.setPrivateAccess(AEDPrivacyCheckbox.isSelected());
    }//GEN-LAST:event_AEDPrivacyCheckboxActionPerformed

    private void PriorityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityComboActionPerformed
        DefaultObjectAttributes.setPriority((mlsPriority) PriorityCombo.getSelectedItem());
    }//GEN-LAST:event_PriorityComboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AEDPrivacyCheckbox;
    private com.mindliner.gui.ObjectAccessControls ObjectAccess;
    private javax.swing.JComboBox PriorityCombo;
    private javax.swing.JCheckBox UpdateDefaults;
    private javax.swing.JLabel jLabel19;
    // End of variables declaration//GEN-END:variables
}
