/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mindliner.cache;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Marius Messerli
 */
public class CacheMonitor extends javax.swing.JFrame {

    CacheMonitorScheduler statusbarScheduler;

    class CacheMonitorScheduler {

        public void start() {
            Timer timer = new Timer("Mindliner Cache Monitor");
            timer.schedule(new MonitorTask(), new Date(), 1000 * 2);
        }

        class MonitorTask extends TimerTask {

            @Override
            public void run() {

                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        CacheDetailObjectsLabel.setText(Integer.toString(CacheEngineStatic.getObjectCount()));
                        CacheDetailsWorkSlotsLabel.setText(Integer.toString(CacheEngineStatic.getWorkUnitCount()));
                        CacheDetailsLinksLabel.setText(Integer.toString(CacheEngineStatic.getLinksCount()));
                        CacheDetailsRootPath.setText(CacheEngineStatic.getCacheDirectoryForCurrentUser());
                    }
                });
            }
        }
    }

    /**
     * Creates new form CacheMonitor
     */
    public CacheMonitor() {
        initComponents();
        configureComponents();
    }

    private void configureComponents() {
        statusbarScheduler = new CacheMonitorScheduler();
        statusbarScheduler.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CacheDetailObjectsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CacheDetailsLinksLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CacheDetailsWorkSlotsLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CacheDetailsRootPath = new javax.swing.JLabel();
        OpenCacheFolderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/resources/General"); // NOI18N
        setTitle(bundle.getString("CacheMonitorTitle")); // NOI18N

        jLabel1.setText(bundle.getString("CacheDetailObjectsLabel")); // NOI18N

        CacheDetailObjectsLabel.setText("jLabel2");

        jLabel2.setText(bundle.getString("CacheDetailsLinksLabel")); // NOI18N

        CacheDetailsLinksLabel.setText("jLabel3");

        jLabel3.setText(bundle.getString("CacheDetailsWorkUnitsLabel")); // NOI18N

        CacheDetailsWorkSlotsLabel.setText("jLabel4");

        jLabel6.setText(bundle.getString("CacheDetailsRootPath")); // NOI18N

        CacheDetailsRootPath.setText("jLabel7");

        OpenCacheFolderButton.setText(bundle.getString("CacheMonitorOpenFolderButton")); // NOI18N
        OpenCacheFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenCacheFolderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CacheDetailObjectsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CacheDetailsLinksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CacheDetailsRootPath, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OpenCacheFolderButton))
                    .addComponent(CacheDetailsWorkSlotsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CacheDetailObjectsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CacheDetailsLinksLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CacheDetailsWorkSlotsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CacheDetailsRootPath)
                    .addComponent(OpenCacheFolderButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenCacheFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenCacheFolderButtonActionPerformed
        try {
            Desktop.getDesktop().open(new File(CacheEngineStatic.getCacheDirectoryForCurrentUser()));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex, "Cache Location", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OpenCacheFolderButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CacheDetailObjectsLabel;
    private javax.swing.JLabel CacheDetailsLinksLabel;
    private javax.swing.JLabel CacheDetailsRootPath;
    private javax.swing.JLabel CacheDetailsWorkSlotsLabel;
    private javax.swing.JButton OpenCacheFolderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
