/*
 * mlSynchProgress.java
 *
 * Created on 2. Juni 2008, 14:12
 */
package com.mindliner.synch;

import com.mindliner.synchronization.MlSynchProgressReporter;

/**
 *
 * @author Marius Messerli
 */
public class SynchProgressDialog extends javax.swing.JDialog implements MlSynchProgressReporter {

    /**
     * Creates new form mlSynchProgress
     */
    public SynchProgressDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    @Override
    public void printLine(String t) {
        String newline = System.getProperty("line.separator");
        OutputText.append(t + newline);
        OutputText.repaint();
        // scroll to end of text pane
        OutputScroller.getVerticalScrollBar().getModel().setValue(10000);
    }

    @Override
    public void clear() {
        OutputText.setText("");
    }

    @Override
    public boolean cancelled() {
        return cancelButtonPressed;
    }
    private boolean cancelButtonPressed = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProgressCancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        OutputScroller = new javax.swing.JScrollPane();
        OutputText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/resources/Synchronization"); // NOI18N
        setTitle(bundle.getString("SynchProgressDialogTitle")); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        ProgressCancelButton.setText(bundle.getString("SynchProgressCancelButton")); // NOI18N
        ProgressCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgressCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ProgressCancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        OutputText.setColumns(20);
        OutputText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        OutputText.setRows(5);
        OutputScroller.setViewportView(OutputText);

        jPanel2.add(OutputScroller);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ProgressCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressCancelButtonActionPerformed
    cancelButtonPressed = true;
}//GEN-LAST:event_ProgressCancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OutputScroller;
    private javax.swing.JTextArea OutputText;
    private javax.swing.JButton ProgressCancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
