/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mindliner.gui;

import com.mindliner.cache.CacheEngineStatic;
import com.mindliner.clientobjects.mlcContact;
import com.mindliner.commands.CommandRecorder;
import com.mindliner.commands.ContactUpdateCommand;
import com.mindliner.commands.ObjectCreationCommand;
import com.mindliner.events.SelectionManager;
import com.mindliner.gui.font.FontPreferences;
import com.mindliner.image.ScaledImageLabel;
import com.mindliner.main.MindlinerMain;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;

/**
 * This dialog lets the user change contact details.
 *
 * @author Marius Messerli
 */
public class ContactEditor extends javax.swing.JDialog {

    private mlcContact contact = null;
    private final ScaledImageLabel profilePictureLabel;

    /**
     * Creates new form ContactEditor
     *
     * @param parent The parent frame for this dialog (or null)
     * @param modal Whether or not this dialog should be modal (blocking) or not
     */
    public ContactEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configureComponents();
        profilePictureLabel = new ScaledImageLabel(128, 128, ScaledImageLabel.InitialZoomPrefs.Fit);
        PicturePanel.add(profilePictureLabel, BorderLayout.CENTER);
        // use the same font that we use for the normal object text editor
        Description.setFont(FontPreferences.getFont(ObjectEditor.FONT_PREFERENCE_KEY));
    }

    private void configureComponents() {
        setLocationRelativeTo(MindlinerMain.getInstance());
        MlDialogUtils.addEscapeListener(this);
    }

    /**
     * Shows the contact editor and lets the user enter the fields
     *
     * @param contact The contact to be edited, specify null if a new contact is
     * to be edited and created
     */
    public void showEditor(mlcContact contact) {
        this.contact = contact;
        setEditorFields();
        setVisible(true);
    }

    public mlcContact getContact() {
        return contact;
    }

    private void setEditorFields() {
        if (contact != null) {
            FirstnameField.setText(contact.getFirstName());
            MiddlenameField.setText(contact.getMiddleName());
            LastnameField.setText(contact.getLastName());
            EmailField.setText(contact.getEmail());
            WorkPhoneField.setText(contact.getPhoneNumber());
            MobilePhoneField.setText(contact.getMobileNumber());
            Description.setText(contact.getDescription());
            if (contact.getProfilePicture() != null) {
                Image img = CacheEngineStatic.getImageSync(contact.getProfilePicture().getId());
                profilePictureLabel.setImage(img);
                ProfilePictureButton.setText("Change Picture");
                profilePictureLabel.repaint();
            } else {
                profilePictureLabel.clear();
                ProfilePictureButton.setText("Choose Picture");
            }
        } else {
            FirstnameField.setText("");
            MiddlenameField.setText("");
            LastnameField.setText("");
            EmailField.setText("");
            WorkPhoneField.setText("");
            MobilePhoneField.setText("");
            profilePictureLabel.clear();
            Description.setText("");
        }
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        // Manually added components are only rendered in of mouse-over event. 
        // we would need to add the component using layouts (see generated code)
        profilePictureLabel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstnameField = new javax.swing.JTextField();
        MiddlenameField = new javax.swing.JTextField();
        LastnameField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        WorkPhoneField = new javax.swing.JTextField();
        MobilePhoneField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ProfilePictureButton = new javax.swing.JButton();
        PicturePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/resources/GeneralEditor"); // NOI18N
        setTitle(bundle.getString("CE_Dialog_Title")); // NOI18N
        setModal(true);

        jLabel1.setText(bundle.getString("CE_FirstName")); // NOI18N

        jLabel2.setText(bundle.getString("CE_Lastname")); // NOI18N

        jLabel3.setText(bundle.getString("CE_Middlename")); // NOI18N

        FirstnameField.setText("jTextField1");

        MiddlenameField.setText("jTextField2");

        LastnameField.setText("jTextField3");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CE_CommTitle"))); // NOI18N

        jLabel4.setText(bundle.getString("CE_WorkEmail")); // NOI18N

        jLabel5.setText(bundle.getString("CE_WorkPhone")); // NOI18N

        jLabel6.setText(bundle.getString("CE_MobilePhone")); // NOI18N

        EmailField.setText("jTextField4");

        WorkPhoneField.setText("jTextField5");

        MobilePhoneField.setText("jTextField6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MobilePhoneField)
                    .addComponent(WorkPhoneField)
                    .addComponent(EmailField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(WorkPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(MobilePhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CE_Notes"))); // NOI18N

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/1616/floppy_disk_blue.png"))); // NOI18N
        SaveButton.setText(bundle.getString("CE_Save")); // NOI18N
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText(bundle.getString("CE_Cancel")); // NOI18N
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        ProfilePictureButton.setText(bundle.getString("CE_ChooseProfilePicture")); // NOI18N
        ProfilePictureButton.setToolTipText(bundle.getString("CE_ChooseProfilePicture_TT")); // NOI18N
        ProfilePictureButton.setPreferredSize(new java.awt.Dimension(128, 128));
        ProfilePictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilePictureButtonActionPerformed(evt);
            }
        });

        PicturePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PicturePanel.setMaximumSize(new java.awt.Dimension(128, 128));
        PicturePanel.setPreferredSize(new java.awt.Dimension(128, 128));
        PicturePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(FirstnameField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 100, Short.MAX_VALUE)
                                .addComponent(ProfilePictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastnameField)
                                    .addComponent(MiddlenameField))))
                        .addGap(18, 18, 18)
                        .addComponent(PicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SaveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MiddlenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(ProfilePictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PicturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        CommandRecorder cr = CommandRecorder.getInstance();
        if (contact == null) {
            ObjectCreationCommand occ = new ObjectCreationCommand(SelectionManager.getLastSelection(), mlcContact.class, "", "");
            cr.scheduleCommand(occ);
            contact = (mlcContact) occ.getObject();
        }
        ContactUpdateCommand cuc = new ContactUpdateCommand(contact,
                FirstnameField.getText(), MiddlenameField.getText(), LastnameField.getText(),
                EmailField.getText(), WorkPhoneField.getText(), MobilePhoneField.getText(),
                Description.getText());
        cr.scheduleCommand(cuc);
        setVisible(false);
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ProfilePictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilePictureButtonActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Image pp = ProfilePictureChooser.changeProfilePicture(contact);
        if (pp != null) {
            profilePictureLabel.setImage(pp);
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_ProfilePictureButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField FirstnameField;
    private javax.swing.JTextField LastnameField;
    private javax.swing.JTextField MiddlenameField;
    private javax.swing.JTextField MobilePhoneField;
    private javax.swing.JPanel PicturePanel;
    private javax.swing.JButton ProfilePictureButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField WorkPhoneField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
