/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mindliner.connector;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Dominic Plangger
 */
public class ConnectorSelectionPanel extends javax.swing.JPanel {
    
    private ConnectorSelectionDialog dialog = null;
    private CloudConnector connector = null;
    private boolean rememberSelection = false;

    /**
     * Creates new form FileDropPanel
     */
    public ConnectorSelectionPanel() {
        initComponents();
        configureComponents();
    }
    
    private void configureComponents() {
        boolean gdriveAuth = GoogleDriveConnector.getInstance().isAuthenticated();
        GooglePopupButton.setEnabled(gdriveAuth);
        
        boolean sftpAuth = SftpConnector.getInstance().isAuthenticated();
        SftpPopupButton.setEnabled(sftpAuth);
        
        addClearPopup(GooglePopupButton, GoogleDriveConnector.getInstance());
        addClearPopup(SftpPopupButton, SftpConnector.getInstance());
    }

    /**
     * Adds a popup menu to the given button that clears the given connector on click.
     */
    private void addClearPopup(final JButton button, final CloudConnector connector) {
        final JPopupMenu menu = new JPopupMenu();
        JMenuItem item = new JMenuItem("Clear credentials");
        item.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                connector.clear();
                button.setEnabled(false);
            }
        });
        menu.add(item);
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                menu.show(button, button.getWidth() / 2, button.getHeight() / 2);
            }
        });
    }

    public CloudConnector getConnector() {
        return connector;
    }

    public boolean isRememberSelection() {
        return rememberSelection;
    }

    public void setDialog(ConnectorSelectionDialog dialog) {
        this.dialog = dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DefaultButton = new javax.swing.JButton();
        GoogleDriveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RememberCheckbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SftpButton = new javax.swing.JButton();
        GooglePopupButton = new javax.swing.JButton();
        SftpPopupButton = new javax.swing.JButton();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+5));
        jLabel1.setText("File Storage");

        DefaultButton.setFont(DefaultButton.getFont());
        DefaultButton.setText("No Action");
        DefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultButtonActionPerformed(evt);
            }
        });

        GoogleDriveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/external/Google-Drive-icon.png"))); // NOI18N
        GoogleDriveButton.setText("Google Drive");
        GoogleDriveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoogleDriveButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(jLabel3.getFont());
        jLabel3.setText("File already on shared location.");

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setText("Upload to Google Drive");

        RememberCheckbox.setFont(RememberCheckbox.getFont());
        RememberCheckbox.setText("Remember my decision");
        RememberCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RememberCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberCheckboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont());
        jLabel2.setText("Choose the file sharing strategy.");

        jLabel5.setFont(jLabel5.getFont());
        jLabel5.setText("Upload to your own server using sFTP");

        SftpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/external/ssh-gnome-icon.png"))); // NOI18N
        SftpButton.setText("SFTP Server");
        SftpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SftpButtonActionPerformed(evt);
            }
        });

        GooglePopupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/external/dropdown-icon.png"))); // NOI18N

        SftpPopupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/external/dropdown-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RememberCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GoogleDriveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SftpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DefaultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GooglePopupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SftpPopupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(DefaultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoogleDriveButton)
                            .addComponent(jLabel4)
                            .addComponent(GooglePopupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SftpButton)
                            .addComponent(jLabel5)))
                    .addComponent(SftpPopupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RememberCheckbox)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultButtonActionPerformed
        connector = new NoActionConnector();
        dialog.setVisible(false);
    }//GEN-LAST:event_DefaultButtonActionPerformed

    private void GoogleDriveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoogleDriveButtonActionPerformed
        connector = GoogleDriveConnector.getInstance();
        dialog.setVisible(false);
    }//GEN-LAST:event_GoogleDriveButtonActionPerformed

    private void RememberCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberCheckboxActionPerformed
        rememberSelection = RememberCheckbox.isSelected();
    }//GEN-LAST:event_RememberCheckboxActionPerformed

    private void SftpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SftpButtonActionPerformed
        connector = SftpConnector.getInstance();
        dialog.setVisible(false);
    }//GEN-LAST:event_SftpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton GoogleDriveButton;
    private javax.swing.JButton GooglePopupButton;
    private javax.swing.JCheckBox RememberCheckbox;
    private javax.swing.JButton SftpButton;
    private javax.swing.JButton SftpPopupButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
