/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mindliner.connector;

import javax.swing.JOptionPane;

/**
 *
 * @author Dominic Plangger
 */
public class SftpAuthenticationPanel extends javax.swing.JPanel {
    
    
    private SftpAuthenticationDialog dialog = null;

    public SftpAuthenticationPanel() {
        initComponents();
    }

    public void setDialog(SftpAuthenticationDialog dialog) {
        this.dialog = dialog;
    }
    
    public void setUsername(String name) {
        UsernameField.setText(name);
    }
    
    public void setServer(String server) {
        ServerField.setText(server);
    }
    
    public void setPassword(String password) {
        PasswordField.setText(password);
    }

    public String getUsername() {
        return UsernameField.getText();
    }
    
    public String getPassword() {
        return new String(PasswordField.getPassword());
    }
    
    public String getServer() {
        return ServerField.getText();
    }
    
    protected void setSubTitle(String text) {
        SubTitle.setText(text);
    }
    
    protected void setTitle(String text) {
        Title.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Title = new javax.swing.JLabel();
        FinishButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ServerField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SubTitle = new javax.swing.JLabel();

        Title.setFont(Title.getFont().deriveFont(Title.getFont().getStyle() | java.awt.Font.BOLD, Title.getFont().getSize()+4));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/gui/GuiElements"); // NOI18N
        Title.setText(bundle.getString("sftpAuthentication")); // NOI18N

        FinishButton.setFont(FinishButton.getFont());
        FinishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/2424/floppy_disk_blue.png"))); // NOI18N
        FinishButton.setText("OK");
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Server URL");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        PasswordField.setToolTipText("");

        SubTitle.setFont(SubTitle.getFont());
        SubTitle.setText(bundle.getString("SftpAuthenticationDescription")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubTitle)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(FinishButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(Title)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UsernameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(ServerField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(3, 3, 3)
                .addComponent(SubTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ServerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(FinishButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        String server = ServerField.getText();
        String username = UsernameField.getText();
        char[] pwd = PasswordField.getPassword();
        if (server == null || server.isEmpty() || username == null || username.isEmpty() || new String(pwd).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all missing values.", "Incomplete form", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dialog.setVisible(false);
    }//GEN-LAST:event_FinishButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinishButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField ServerField;
    private javax.swing.JLabel SubTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
