/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mindliner.prefs;

import com.mindliner.entities.Colorizer;
import com.mindliner.gui.color.BaseColorizer;
import com.mindliner.gui.color.ColorManager;
import com.mindliner.gui.tablemanager.MlObjectTable;
import com.mindliner.gui.tablemanager.TableColumnManager;
import javax.swing.DefaultComboBoxModel;

/**
 *This is the GUI that lets the user choose the color driver for the specified table.
 * 
 * @author Marius Messerli
 */
public class TableColorPreferences extends javax.swing.JDialog {

    private MlObjectTable table = null;
    
    /**
     * Creates new form TableColorPreferences
     */
    public TableColorPreferences(java.awt.Frame parent, boolean modal, MlObjectTable table) {
        super(parent, modal);
        initComponents();
        this.table = table;
        configureComponents();
    }
    
    private void configureComponents() {
        DefaultComboBoxModel boxmodel = new DefaultComboBoxModel();
        for (Colorizer.ColorDriverAttribute attr : TableColumnManager.getSupportedAttributes(table)) {
            boxmodel.addElement(attr);
        }
        ColorDriverCombo.setModel(boxmodel);
        ColorDriverCombo.setSelectedItem(table.getColorizer().getDriverAttribute());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        ColorDriverCombo = new javax.swing.JComboBox();
        EditColorSchemes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/mindliner/resources/Tables"); // NOI18N
        setTitle(bundle.getString("TableColorPreferencesTitle")); // NOI18N

        jLabel25.setText(bundle.getString("PreferenceDialogTableColorDriver")); // NOI18N

        ColorDriverCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ColorDriverCombo.setToolTipText(bundle.getString("TableConfigColorDriver_TT")); // NOI18N
        ColorDriverCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDriverComboActionPerformed(evt);
            }
        });

        EditColorSchemes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mindliner/img/icons/1616/edit-2.png"))); // NOI18N
        EditColorSchemes.setText(bundle.getString("TableManagerEditColorSchemesButton")); // NOI18N
        EditColorSchemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditColorSchemesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(26, 26, 26)
                        .addComponent(ColorDriverCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(EditColorSchemes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ColorDriverCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditColorSchemes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorDriverComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDriverComboActionPerformed
        setVisible(false);
        if (table != null) {
            BaseColorizer colorizer = ColorManager.getColorizerForType((Colorizer.ColorDriverAttribute) ColorDriverCombo.getSelectedItem());
            if (colorizer != null) {
                table.setColorizer(colorizer);
            }
        }
    }//GEN-LAST:event_ColorDriverComboActionPerformed

    private void EditColorSchemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditColorSchemesActionPerformed
        setVisible(false);
        MlMainPreferenceEditor.showDialog();
    }//GEN-LAST:event_EditColorSchemesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ColorDriverCombo;
    private javax.swing.JButton EditColorSchemes;
    private javax.swing.JLabel jLabel25;
    // End of variables declaration//GEN-END:variables
}
